export { handleAdmins } from './admins';
export { handleSettings } from './settings';
export { handleCategories } from './categories';
export { handleProducts } from './products';
export { handleFaqs } from './faqs';
export { handleBranches } from './branches';
export { handleMenuConfig } from './menu-config';
export { handleMessages } from './messages';
export { handleAiLogs } from './ai-logs';
export { handleAiTest } from './ai-test';
export { handleAiChatRoute } from './ai-chat';
export type { ResourceHandler, ResourceCtx } from './types';
