name = "azadi-coffee-bot"
main = "src/index.ts"
compatibility_date = "2026-08-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
# TELEGRAM_BOT_TOKEN and SECRET_TOKEN will be set as secrets

[[d1_databases]]
binding = "DB"
database_name = "azadi-db"
database_id = "2c020279-a453-4105-984d-c09bdda89819"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "CACHE"
id = "cf01f801bdae488b9196782f2541d288"
