-- Baseline migration: captures the production D1 schema as of 2026-08-13.
-- Generated by comparing sqlite_master output against src/database/schema.ts.
-- All prior migrations (0000-0009) are archived in drizzle/archive/.

-- ===========================================================================
-- Tables
-- ===========================================================================

CREATE TABLE IF NOT EXISTS `branches` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `name` text NOT NULL,
  `address` text NOT NULL,
  `phone` text,
  `location` text,
  `opening_hours` text,
  `is_active` integer DEFAULT true
);

CREATE TABLE IF NOT EXISTS `categories` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `name` text NOT NULL,
  `description` text,
  `emoji` text,
  `sort_order` integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `products` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `branch_id` integer,
  `category_id` integer NOT NULL,
  `name` text NOT NULL,
  `description` text,
  `price` real,
  `stock` integer DEFAULT 0 NOT NULL,
  `unit` text DEFAULT 'item' NOT NULL,
  `image_url` text,
  `available` integer DEFAULT true,
  `featured` integer DEFAULT false,
  `price_on_request` integer DEFAULT false,
  `is_seasonal` integer DEFAULT false,
  `size_options` text,
  `syrup_options` text,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  `calories` integer,
  `allergens` text,
  `caffeine_mg` integer,
  FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`) ON UPDATE no action ON DELETE no action,
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE IF NOT EXISTS `coffee_details` (
  `product_id` integer PRIMARY KEY NOT NULL,
  `origin` text,
  `farm` text,
  `altitude` text,
  `processing` text,
  `variety` text,
  `roast_level` text,
  `flavor_notes` text,
  `recommended_brew` text,
  `acidity` text,
  `body` text,
  `brew_guide` text,
  FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE IF NOT EXISTS `faq` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `question` text NOT NULL,
  `answer` text NOT NULL
);

CREATE TABLE IF NOT EXISTS `settings` (
  `key` text PRIMARY KEY NOT NULL,
  `value` text NOT NULL
);

CREATE TABLE IF NOT EXISTS `ai_conversation_logs` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `user_id` text NOT NULL,
  `question` text NOT NULL,
  `response` text NOT NULL,
  `timestamp` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `sessions` (
  `key` text PRIMARY KEY NOT NULL,
  `value` text NOT NULL
);

CREATE TABLE IF NOT EXISTS `admins` (
  `telegram_id` integer PRIMARY KEY NOT NULL,
  `role` text DEFAULT 'super_admin' NOT NULL,
  `category_id` integer,
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`)
);

CREATE TABLE IF NOT EXISTS `menu_config` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `category_id` integer NOT NULL REFERENCES `categories`(`id`) ON DELETE CASCADE,
  `menu_section` text NOT NULL,
  `display_order` integer DEFAULT 0 NOT NULL,
  `is_visible` integer DEFAULT 1 NOT NULL,
  `button_label` text,
  `special_message` text,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `user_state` (
  `telegram_id` text PRIMARY KEY,
  `first_seen_at` integer NOT NULL,
  `last_seen_at` integer NOT NULL,
  `visits_total` integer NOT NULL DEFAULT 0,
  `streak_days` integer NOT NULL DEFAULT 0,
  `last_quiz_at` integer
);

CREATE TABLE IF NOT EXISTS `favorites` (
  `telegram_id` text NOT NULL,
  `product_id` integer NOT NULL REFERENCES `products`(`id`) ON DELETE CASCADE,
  `created_at` integer NOT NULL,
  PRIMARY KEY (`telegram_id`, `product_id`)
);

CREATE TABLE IF NOT EXISTS `messages` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `telegram_id` text NOT NULL,
  `sender_name` text,
  `sender_email` text,
  `content` text NOT NULL,
  `rating` integer,
  `is_anonymous` integer DEFAULT false,
  `is_read` integer DEFAULT false,
  `replied` integer DEFAULT false,
  `reply_text` text,
  `replied_at` integer,
  `created_at` integer NOT NULL
);

-- ===========================================================================
-- Indexes (matches production D1 state)
-- ===========================================================================

CREATE INDEX IF NOT EXISTS `idx_products_category` ON `products` (`category_id`);
CREATE INDEX IF NOT EXISTS `idx_products_available` ON `products` (`available`);
CREATE INDEX IF NOT EXISTS `idx_products_featured` ON `products` (`featured`);
CREATE INDEX IF NOT EXISTS `idx_products_seasonal` ON `products` (`is_seasonal`);
CREATE INDEX IF NOT EXISTS `idx_products_cat_avail` ON `products` (`category_id`, `available`);
CREATE INDEX IF NOT EXISTS `idx_ai_logs_user_ts` ON `ai_conversation_logs` (`user_id`, `timestamp`);
CREATE INDEX IF NOT EXISTS `idx_messages_unread` ON `messages` (`is_read`);
CREATE INDEX IF NOT EXISTS `idx_messages_created` ON `messages` (`created_at` DESC);
CREATE INDEX IF NOT EXISTS `idx_messages_user` ON `messages` (`telegram_id`);
-- Production-only indexes (not in code schema but present in D1):
CREATE INDEX IF NOT EXISTS `idx_favorites_telegram_id` ON `favorites` (`telegram_id`);
CREATE INDEX IF NOT EXISTS `idx_favorites_user` ON `favorites` (`telegram_id`, `created_at` DESC);
CREATE INDEX IF NOT EXISTS `idx_messages_replied` ON `messages` (`replied`);
CREATE INDEX IF NOT EXISTS `idx_user_state_last_seen` ON `user_state` (`last_seen_at`);
